repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v3.1.0
        hooks:
        -   id: trailing-whitespace
    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v1.5.3
        hooks:
        -   id: autopep8
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.782
        hooks:
        -   id: mypy
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v5.1.4
        hooks:
        -   id: isort
