name: Build & test Airflow
on:
  workflow_dispatch:
jobs:

  build:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    
    steps:
  
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt build
        python -m build
        pip install airflow-tm1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DUSERNAME }}
        password: ${{ secrets.DPASSWORD }}
    
    - name: Install & run Airflow
      run: |
        cd tests_integration
        echo -e "AIRFLOW_UID=$(id -u)" > .env
        docker compose up -d airflow-init
        docker compose up -d --build
    
    - name: Stop docker containers
      run: |
        cd tests_integration
        docker compose down
        
